spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 579371789524-t4085u2d9ichms6nttc9g9uru4en5k4s.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: l1yxRHCuLgDr2fa8mQk3
            client-secret: GqWllIFNfi
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: 3c3b4d881b03c7074c49fded6b349cb2
            client-secret: lt79AkfEGdr6mMUawLdexgx9OO1wfOTz
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


# Spoonacular API

# API keys
spoonacular:
  api:
    key: 4491a88dd7dd4ce4888626baf188b460

edamam:
  recipe:
    api:
      key: eb761fc17dd7daa82de4f6418e509da4
    app:
      id: 5ee36020

  nutrition:
    api:
      key: 9135ed3d8a6b8ffc62a0125e7b2faebd
    app:
      id: a2f6e0bf

  meal:
    api:
      key: 704a60536bb81c27ea96f9ca84733d8b
    app:
      id: 4fabdf73